version: '2'
services:
  wp-sqlite:
    image: "emcniece/wp-sqlite"
    tty: true
    stdin_open: true
    ports:
      - ${PORT}:80
    labels:
      rgon.domain: ${DOMAIN}
      rgon.ssl: ${SSL}
      rgon.redirect: ${REDIRECT}
wp-sqlite:
  scale: 1