name: Usenet Media Stack
description: |
  Plex, Sonarr, Radarr for Usenet and torrents
version: 0.0.1
category: Applications
maintainer: "Eric McNiece <emcniece@gmail.com>"
projectURL: https://github.com/emcniece/rancher-catalog
