version: '2'

services:
  nginx:
    image: emcniece/nginx-cache-purge-wp:1.13-alpine
    ports:
    - ${PORT}:80
    volumes_from:
    - wp-fpm
    labels:
      rgon.ssl: ${SSL}
      rgon.domain: ${HOST}
      rgon.redirect: ${REDIRECT}

  mysql-helper:
    image: emcniece/mysql-helper:0.0.4
    links:
    - mysql:mysql
    volumes:
    - files:/target
    - backup:/backup
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DB: ${MYSQL_NAME}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_PORT: 3306
      SQL_GZ: true
      INIT_RESTORE_LATEST: true
      BACKUP_DIR: "/backup/${HOST}"

  wp-fpm:
    image: emcniece/wordpress:4-php7.1-fpm-alpine
    tty: true
    stdin_open: true
    links:
    - mysql:mysql
    - redis:redis
    - nginx:nginx
    volumes:
    - files:/var/www/html
    labels:
      io.rancher.sidekicks: nginx, mysql-helper
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_NAME: ${MYSQL_NAME}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASS}
      WPFPM_WP_REDIS_HOST: redis
      WPFPM_RT_WP_NGINX_HELPER_CACHE_PATH: "/tmp/cache"

  redis:
    image: redis:3-alpine

  mysql:
    image: mariadb
    command: mysqld --innodb-buffer-pool-size=${INNODB_BUF}M
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASS}

volumes:
  files:
    driver: ${STORAGE_LOCAL}
  backup:
    driver: ${STORAGE_REMOTE}
    external: ${STORAGE_REMOTE_EXTERNAL}
