name: Concourse
description: |
  Continuous Integration
version: 0.0.2
category: Continuous Integration
maintainer: "Eric McNiece <emcniece@gmail.com>"
projectURL: https://github.com/emcniece/rancher-catalog