name: Concourse
description: CI that scales with your project.
version: 0.0.8
category: Continuous Integration
maintainer: "Eric McNiece <emcniece@gmail.com>"
projectURL: https://github.com/emcniece/rancher-catalog