.catalog:
  name: Concourse
  version: v0.0.5
  description: CI that scales with your project.
  maintainer: "Eric McNiece <emcniece@gmail.com>"
  uuid: cc-0
  questions:
  - variable: "DIR"
    label: "Storage Directory"
    description: For storing access keys
    required: false
    type: "string"
  - variable: "DOMAIN_NAME"
    description: |
      Domain at which server will be accessible on the Internet.
      E.g. https://concourse.example.com (no trailing slash). Include a port if needed for access.
    label: "Full Domain Name"
    required: true
    type: "string"
  - variable: "PORT"
    description: |
      Port for HTTP traffic. Forwards internally to 8888.
    label: "HTTP Port"
    required: false
    type: "int"
  - variable: "USER"
    label: "Login Username"
    description: Default username for first login
    required: true
    type: "string"
    default: "concourse"
  - variable: "PASSWORD"
    label: "Login Password"
    description: Password for first login (defaults to "changeme")
    required: true
    type: "password"
    default: "changeme"
  - variable: "GITHUB_CLIENT_ID"
    label: "Github Client ID"
    description: For enabling Github OAuth. Callback is https://domain.com/auth/github/callback
    required: false
    type: "string"
  - variable: "GITHUB_CLIENT_SECRET"
    label: "Github Client Secret"
    required: false
    type: "password"
  - variable: "GITHUB_AUTH_TEAM"
    label: "Github Team"
    description: Name of your team (ie. concourse/Pivotal)
    required: false
    type: "string"