version: '2'
services:
  nginx:
    image: emcniece/nginx-cache-purge-wp:1.13-alpine
    ports:
    - ${PORT}:80
    volumes:
    - files:/var/www/html
    labels:
      rgon.ssl: ${SSL}
      rgon.domain: ${HOST}
      rgon.redirect: ${REDIRECT}

  mysql-helper:
    image: emcniece/mysql-helper:0.0.4
    volumes:
    - files:/target
    - backup:/backup
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DB: ${MYSQL_NAME}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_PORT: ${MYSQL_PORT}
      SQL_GZ: 'true'
      INIT_RESTORE_LATEST: 'true'
      BACKUP_DIR: "/backup/${HOST}"

  wp-fpm:
    image: emcniece/wordpress:4-php7.1-fpm-alpine
    tty: true
    stdin_open: true
    links:
    - redis:redis
    - nginx:nginx
    volumes:
    - files:/var/www/html
    labels:
      io.rancher.sidekicks: nginx, mysql-helper
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_NAME: ${MYSQL_NAME}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASS}
      WORDPRESS_DB_PORT: ${MYSQL_PORT}
      WPFPM_WP_REDIS_HOST: redis
      WPFPM_RT_WP_NGINX_HELPER_CACHE_PATH: "/tmp/cache"

  redis:
    image: redis:3-alpine

volumes:
  files:
    driver: ${STORAGE_LOCAL}
  backup:
    driver: ${STORAGE_REMOTE}
    external: true
