version: '2'
catalog:
  name: WordPress PHP7
  version: 0.0.2
  description: |
    One-click WordPress w/ PHP7-FPM, Redis, Nginx
  maintainer: "Eric McNiece <emcniece@gmail.com>"

  questions:
    - variable: "DIR"
      label: "Storage directory"
      description: "Path of shared storage to use for WordPress and the import files. No trailing slash!"
      required: true
      type: "string"
    - variable: "PORT"
      description: |
        Port for HTTP traffic. Leave blank to let Rancher choose a random port.
      label: "Port"
      required: false
      type: "int"

    - variable: "MYSQL_HOST"
      description: "Database Host"
      label: "DB Host"
      required: true
      type: "string"
    - variable: "MYSQL_PORT"
      description: "Database Port"
      label: "DB Port"
      required: true
      type: "int"
      default: 3306
    - variable: "MYSQL_NAME"
      description: "Database Name"
      label: "DB Name"
      required: true
      type: "string"
      default: "wordpress"
    - variable: "MYSQL_USER"
      description: "Database User"
      label: "DB User"
      required: true
      type: "string"
      default: "wordpress"
    - variable: "MYSQL_PASS"
      description: "Database Password"
      label: "DB Password"
      required: true
      type: "password"
      default: "wordpress"

    - variable: "HOST"
      description: "RGON-Proxy Hostname for WordPress (FQDN). Also used for helper backup directory"
      label: "Hostname"
      required: false
      type: "string"
    - variable: "SSL"
      description: "Enable RGON-Proxy SSL certificate"
      label: "SSL Certificate"
      required: true
      type: "boolean"
      default: false
    - variable: "REDIRECT"
      label: "HTTPS Redirect"
      description: "Enable http/https redirects for RGON-Proxy"
      required: false
      default: "http"
      type: "enum"
      options:
        - http
        - https

    - variable: STORAGE_LOCAL
      label: Local Storage Driver
      description: "Options: 'local' or 'nfs' (no host directory support)"
      type: "string"
      default: "local"
    - variable: STORAGE_REMOTE
      label: Remote Storage Driver
      description: "Options: 'local' (named volume) or 'rancher-nfs' for Rancher-managed storage"
      type: "string"
      default: "rancher-nfs"

services:
  nginx:
    scale: 1
  wp-fpm:
    scale: 1
  mysql-helper:
    scale: 1
  redis:
    scale: 1
